---
dist: xenial
sudo: required

language: python

services:
  - docker

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37

install:
  - pip install tox-travis
  - pip install docker-py

script: tox
